/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function HeadModel(props) {
  const { nodes, materials } = useGLTF("/models/head-model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material}>
        <meshToonMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/head-model.glb");
